// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwYFfv03IrFUuR2VE33VahBvWpeczk_HU',
    appId: '1:1033971395242:web:2d5fce3541bdc5c9c07ed3',
    messagingSenderId: '1033971395242',
    projectId: 'loginapp-6096b',
    authDomain: 'loginapp-6096b.firebaseapp.com',
    storageBucket: 'loginapp-6096b.appspot.com',
    measurementId: 'G-JMLRKYYNGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi18lG0d7u6kAq4mVI8mw0lSK4RfbOh7k',
    appId: '1:1033971395242:android:385c965834290691c07ed3',
    messagingSenderId: '1033971395242',
    projectId: 'loginapp-6096b',
    storageBucket: 'loginapp-6096b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlU5uKpfTWsWWZizY8RsTmPuJG7NvROrg',
    appId: '1:1033971395242:ios:66d354bdb054fae7c07ed3',
    messagingSenderId: '1033971395242',
    projectId: 'loginapp-6096b',
    storageBucket: 'loginapp-6096b.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlU5uKpfTWsWWZizY8RsTmPuJG7NvROrg',
    appId: '1:1033971395242:ios:f2db2f42154db916c07ed3',
    messagingSenderId: '1033971395242',
    projectId: 'loginapp-6096b',
    storageBucket: 'loginapp-6096b.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
